import math as _math

EPSILON = 1e-8

DEFAULT_SIMULATION_FREQUENCY = 90
SIMULATION_FREQUENCY_LOW = 30
SIMULATION_FREQUENCY_HIGH = 150
DEFAULT_MAX_SIMULATION_COUNT_PER_FRAME = 3
MAX_SIMULATION_COUNT_LOW = 1
MAX_SIMULATION_COUNT_HIGH = 5

MAX_DISTANCE_RATIO_FUTURE_PREDICTION = 1.3

FRICTION_MASS = 3.0
DEPTH_MASS = 5.0
FRICTION_DAMPING_RATE = 0.6

TETHER_COMPRESSION_STIFFNESS = 1.0
TETHER_STRETCH_STIFFNESS = 1.0
TETHER_STRETCH_LIMIT = 0.03
TETHER_STIFFNESS_WIDTH = 0.3
TETHER_COMPRESSION_VELOCITY_ATTENUATION = 0.7
TETHER_STRETCH_VELOCITY_ATTENUATION = 0.7

DISTANCE_VELOCITY_ATTENUATION = 0.3
DISTANCE_HORIZONTAL_STIFFNESS = 0.5

TRIANGLE_BENDING_MAX_ANGLE = 120.0
VOLUME_MIN_ANGLE = 90.0
VOLUME_SIGN = 100
VOLUME_SCALE = 1000.0

ANGLE_LIMIT_ITERATION = 3
ANGLE_LIMIT_ATTENUATION = 0.9
ANGLE_LIMIT_ROTATION_RATIO = 0.4

MAX_MOVEMENT_SPEED_LIMIT = 10.0
MAX_ROTATION_SPEED_LIMIT = 1440.0
MAX_PARTICLE_SPEED_LIMIT = 10.0

COLLIDER_DYNAMIC_FRICTION_RATIO = 1.0
COLLIDER_STATIC_FRICTION_RATIO = 1.0

SELF_COLLISION_SOLVER_ITERATION = 4
SELF_COLLISION_FIXED_MASS = 100.0
SELF_COLLISION_FRICTION_MASS = 10.0
SELF_COLLISION_CLOTH_MASS = 50.0
SELF_COLLISION_SCR = 2.0
SELF_COLLISION_INTERSECT_DIV = 2
SELF_COLLISION_THICKNESS_MIN = 0.001
SELF_COLLISION_THICKNESS_MAX = 0.05
SELF_COLLISION_UNIFORM_GRID_SCALE = 3.0
SELF_COLLISION_POINT_TRIANGLE_ANGLE_COS = _math.cos(_math.radians(60.0))

WIND_MAX_TIME = 10000.0
WIND_BASE_SPEED = 7.5
WIND_TURBULENCE_ANGLE = 45.0
WIND_ZONE_SLOTS = 4
WIND_ZONE_MIN_MAIN = 1e-6
WIND_MIN_SPEED = 0.01

BONE_SPRING_DISTANCE_STIFFNESS = 0.5
BONE_SPRING_TETHER_COMPRESSION_LIMIT = 0.8
BONE_SPRING_COLLISION_FRICTION = 0.5
BONE_SPRING_FIX_MASS = 10.0
BONE_CLOTH_FIX_MASS = 50.0

PROXY_MESH_BONE_TRIANGLE_ANGLE = 120.0
SAME_SURFACE_ANGLE = 80.0

DISTANCE_CULLING_MAX_LENGTH = 100.0

CURVE_LUT_SAMPLES = 16

ATTR_FIXED = 0x01
ATTR_MOVE = 0x02
ATTR_INVALID_MOTION = 0x08
ATTR_DISABLE_COLLISION = 0x10
ATTR_ZERO_DISTANCE = 0x20
ATTR_TRIANGLE = 0x80

COLLIDER_SPHERE = 0
COLLIDER_CAPSULE = 1
COLLIDER_PLANE = 2

COLLISION_NONE = 0
COLLISION_POINT = 1
COLLISION_EDGE = 2

SELF_MODE_NONE = 0
SELF_MODE_FULL_MESH = 2

TELEPORT_NONE = 0
TELEPORT_RESET = 1
TELEPORT_KEEP = 2

FORCE_NONE = 0
FORCE_VELOCITY_ADD = 1
FORCE_VELOCITY_ADD_WITHOUT_DEPTH = 2
FORCE_VELOCITY_CHANGE = 3
FORCE_VELOCITY_CHANGE_WITHOUT_DEPTH = 4

KIND_POINT = 0
KIND_EDGE = 1
KIND_TRIANGLE = 2

GRID_KEY_BIAS = 1 << 20
GRID_KEY_IGNORE = 1 << 62


def simulation_power(frequency):
    t = DEFAULT_SIMULATION_FREQUENCY / float(frequency)
    return (
        t,
        t ** 0.5 if t > 1.0 else t,
        t ** 0.3 if t > 1.0 else t,
        t ** 1.8,
    )
